# Generated by Django 6.0.3 on 2026-07-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0016_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
